import React from "react";
import "./globals.css";
import { Kumbh_Sans as KumbhSans } from "next/font/google";

const kumbhSans = KumbhSans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={kumbhSans.className}>{children}</body>
    </html>
  );
}
